spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/store?currentSchema=dataexplorer1
    username: dataexplorer1
    password: 2MuchTime
  jpa:
    show-sql: true
    properties:
      hibernate:
        default_schema: dataexplorer1

websiteUrl: https://www.custom-built-apps.com/store

env: production
baseUrl: /store
server:
  port: 8080
  address: 0.0.0.0
  forward-headers-strategy: native
  servlet:
    context-path: ${baseUrl}

springdoc:
  swagger-ui:
    url: ${websiteUrl}/swagger-ui/index.html

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}